### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by yikaa** [SonderXiaoming/huannai_plugin_fortune#11]
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `fortune_path = WindowsPath('C:/新建文件夹/HoshinoBot-master/hoshino/modules/huannai_plugin_fortune/resource')`. All model fields require a type annotation; if `fortune_path` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

ERROR: Failed to import "hoshino.modules.huannai_plugin_fortune.config", error: A non-annotated attribute was detected: `fortune_path = WindowsPath('C:/新建文件夹/HoshinoBot-master/hoshino/modules/huannai_plugin_fortune/resource')`. All model fields require a type annotation; if `fortune_path` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
具体报错信息，是不是需要注释什么？

**Comment by SonderXiaoming** [comment]
fortune_path 前面加":Path"

**Comment by yikaa** [comment]
![图片](https://github.com/SonderXiaoming/huannai_plugin_fortune/assets/86066268/a7d1c00b-99fc-418b-aa8b-2e6abc6288d2)
有另外的错误了

**Comment by SonderXiaoming** [comment]
#9

**Comment by yikaa** [comment]
好的感谢，已解决
