### ISSUE TITLE
ERROR: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by yuyue31** [SonderXiaoming/huannai_plugin_fortune#4]
请问遇到这个错误如何消除，后台显示了这个报错信息

**Comment by yuyue31** [comment]
大佬我不知道图片咋上传，上面显示的这些
  File "F:\bot\HoshinoBot\hoshino\modules\huannai_plugin_fortune-main\__init__.py", line 5, in <module>
    from .data_source import fortune_manager
  File "F:\bot\HoshinoBot\hoshino\modules\huannai_plugin_fortune-main\data_source.py", line 12, in <module>
    from .extra_config_utils import group_rule_list2str, group_rule_str2list
  File "F:\bot\HoshinoBot\hoshino\modules\huannai_plugin_fortune-main\extra_config_utils.py", line 1, in <module>
    def group_rule_str2list(rulestr: str) -> list[str]:
TypeError: 'type' object is not subscriptable

**Comment by SonderXiaoming** [comment]
你的py版本？

**Comment by yuyue31** [comment]
好像都没法用？下面也确实显示这个插件已经运行了



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 14, 2022 03:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SonderXiaoming/huannai_plugin_fortune] ERROR: 'type' object isnot subscriptable (Issue #4)




 
这是哪个指令触发的报错

**Comment by SanaChitose** [comment]
同样的问题
![图片](https://user-images.githubusercontent.com/102790983/207478718-95444c98-109d-4275-a504-988d2b36ea0b.png)
 python版本是3.8.3
![图片](https://user-images.githubusercontent.com/102790983/207478569-4ec2a000-0e2d-4938-83f9-52c941f72fec.png)

**Comment by SonderXiaoming** [comment]
推荐py版本3.10
貌似是你们py版本太低
不想升级可以把extra_config_utils
第一行 -> list[str]
第七行list[str]
这两个删除

**Comment by SanaChitose** [comment]
> 推荐py版本3.10 貌似是你们py版本太低 不想升级可以把extra_config_utils 第一行 -> list[str] 第七行list[str] 这两个删除

回复 删除后 可以使用了

**Comment by yuyue31** [comment]
大佬您好，已经能运行了，十分感谢



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 14, 2022 09:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SonderXiaoming/huannai_plugin_fortune] ERROR: 'type' object isnot subscriptable (Issue #4)




 
推荐py版本3.10
 貌似是你们py版本太低
 不想升级可以把extra_config_utils
 第一行 -&gt; list[str]
 第七行list[str]
 这两个删除

**Comment by whitegive99** [comment]
File "C:\Users\Administrator\Music\HoshinoBot\hoshino\modules\huannai_plugin_f
ortune\__init__.py", line 5, in <module>
    from .data_source import fortune_manager
  File "C:\Users\Administrator\Music\HoshinoBot\hoshino\modules\huannai_plugin_f
ortune\data_source.py", line 11, in <module>
    from .extra_config_utils import group_rule_list2str, group_rule_str2list
  File "C:\Users\Administrator\Music\HoshinoBot\hoshino\modules\huannai_plugin_f
ortune\extra_config_utils.py", line 7
    def group_rule_list2str(group_rule_list : ) -> str:
                                              ^
SyntaxError: invalid syntax
删除后依然报错

**Comment by SonderXiaoming** [comment]
> File "C:\Users\Administrator\Music\HoshinoBot\hoshino\modules\huannai_plugin_f ortune__init__.py", line 5, in from .data_source import fortune_manager File "C:\Users\Administrator\Music\HoshinoBot\hoshino\modules\huannai_plugin_f ortune\data_source.py", line 11, in from .extra_config_utils import group_rule_list2str, group_rule_str2list File "C:\Users\Administrator\Music\HoshinoBot\hoshino\modules\huannai_plugin_f ortune\extra_config_utils.py", line 7 def group_rule_list2str(group_rule_list : ) -> str: ^ SyntaxError: invalid syntax 删除后依然报错

应该把冒号一起删除
