### ISSUE TITLE
疑似读配置文件错误

### ISSUE THREAD

**Issue by SanaChitose** [SonderXiaoming/huannai_plugin_fortune#8]
![图片](https://user-images.githubusercontent.com/102790983/228123125-22f7e698-8bae-43a2-9829-3d70bb6c0529.png)
因为py版本是3.8，因此对extra_config_utils.py中做了调整
![图片](https://user-images.githubusercontent.com/102790983/228123292-34ce69a2-bd28-497a-810a-92f58bcadfd3.png)
一直用着没问题，重启一次hoshino后就一直报这个错了，试过重新导入插件，同样报错

**Comment by SonderXiaoming** [comment]
https://raw.githubusercontent.com/MinatoAquaCrews/nonebot_plugin_fortune/master/nonebot_plugin_fortune/resource，download.py里面的base url改成上面这个，这个是fastgit寄了的缘故

**Comment by SanaChitose** [comment]
![图片](https://user-images.githubusercontent.com/102790983/228159486-a15246a2-f3dc-4826-85ea-2bd4e5379c1f.png)
retry了3次以后寄了 是我网络的问题吗

**Comment by SanaChitose** [comment]
看上去确实是网络波动的问题，只要确保自己可以访问https://raw.githubusercontent.com/MinatoAquaCrews/nonebot_plugin_fortune/master/nonebot_plugin_fortune/resource/fortune/copywriting.json
应该就能正常使用了
