### ISSUE TITLE
如果导入模块时候像我一样报错ERROR：' type' object is not subscribable，可以这么解决

### ISSUE THREAD

**Issue by wuyeyanjiuyuan** [SonderXiaoming/huannai_plugin_fortune#9]
将原来的extra_config_utils.py，改成以下的，
![image](https://user-images.githubusercontent.com/57974682/232202985-6c352846-691a-4ee9-91b7-5ff60441af02.png)

`from typing import List

def group_rule_str2list(rulestr: str) -> List[str]:
    if rulestr[-1] == ',':
        rulestr = rulestr[:-1]
    return rulestr.split(",")

def group_rule_list2str(group_rule_list: List[str]) -> str:
    gs = ""
    for gr in group_rule_list:
        gs = gs + gr + ","
    gs = gs[:-1]
    return gs
`

**Comment by SonderXiaoming** [comment]
你应该pr，不是开issue

**Comment by wuyeyanjiuyuan** [comment]
> 你应该pr，不是开issue

不好意思，没用过这个pr下次遇到这种情况就用这个，感谢大佬的模块
